spring:
  application:
    name: zuul-route
  cache:
    ehcache:
      config: classpath:ehcache.xml
  cloud:
    loadbalancer:
      retry:
        enabled: true

server:
  port: 30004

eureka:
  client:
    service-url:
      defaultZone: http://eureka-demo:8030/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    metadata-map:
      gateway: ts-route-service

zuul:
  RibbonRoutingFilter:
    route:
      disable: true
  routes:
    zuul:
      path: /frecovery/**
      service-id: zuul-route

    route:
      path: /api/v1/routeservice/**
      service-id: ts-route-service
      strip-prefix: false
  sensitive-headers:

ribbon:
  ConnectionTimeout: 10000
  ReadTimeout: 600000


logging:
  level:
    io.ztbeike.ffr4ms: debug