server:
  port: 12342

spring:
  application:
    name: ts-user-service
  data:
    mongodb:
      host: ts-user-mongo
      database: ts-user-mongo
      port: 27017

swagger:
  controllerPackage: user.controller

eureka:
  client:
    service-url:
      defaultZone: http://eureka-demo:8030/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}