spring:
  application:
    name: ts-zuul-train
  cache:
    ehcache:
      config: classpath:ehcache.xml
  cloud:
    loadbalancer:
      retry:
        enabled: true

server:
  port: 30002

eureka:
  client:
    service-url:
      defaultZone: http://eureka-demo:8030/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

zuul:
  RibbonRoutingFilter:
    route:
      disable: true
  routes:
    zuul:
      path: /zuulApi/**
      service-id: ts-zuul-train

    station:
      path: /api/v1/trainservice/**
      service-id: ts-train-service
      strip-prefix: false
