spring:
  application:
    name: zuul-order
  cache:
    ehcache:
      config: classpath:ehcache.xml
  cloud:
    loadbalancer:
      retry:
        enabled: true

server:
  port: 30008

eureka:
  client:
    service-url:
      defaultZone: http://eureka-demo:8030/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

zuul:
  RibbonRoutingFilter:
    route:
      disable: true
  routes:
    zuul:
      path: /zuulApi/**
      service-id: zuul-order

    price:
      path: /api/v1/orderservice/**
      service-id: ts-order-service
      strip-prefix: false
  sensitive-headers:

ribbon:
  ConnectionTimeout: 10000
  ReadTimeout: 600000