spring:
  application:
    name: zuul-inside-payment
  cache:
    ehcache:
      config: classpath:ehcache.xml
  cloud:
    loadbalancer:
      retry:
        enabled: true

server:
  port: 30007

eureka:
  client:
    service-url:
      defaultZone: http://eureka-demo:8030/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    metadata-map:
      gateway: ts-inside-payment-service

zuul:
  RibbonRoutingFilter:
    route:
      disable: true
  routes:
    zuul:
      path: /frecovery/**
      service-id: zuul-inside-payment

    inside-payment:
      path: /api/v1/inside_pay_service/**
      service-id: ts-inside-payment-service
      strip-prefix: false

  sensitive-headers:

ribbon:
  ConnectionTimeout: 10000
  ReadTimeout: 600000

info:
  getway: ts-inside-payment-service
  port: ${server.port}

logging:
  level:
    io.ztbeike.ffr4ms: debug