spring:
  application:
    name: ts-price-service
  data:
    mongodb:
      host: ts-price-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017


# HTTP Server
server:
  port: 16579  # HTTP (Tomcat) port

swagger:
  controllerPackage: price.controller

eureka:
  client:
    service-url:
      defaultZone: http://eureka-demo:8030/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    metadata-map:
      leaf: true

logging:
  level:
    io.ztbeike.ffr4ms: debug