spring:
  application:
    name: ts-train-service
  data:
    mongodb:
      host: ts-train-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017

# HTTP Server
server:
  port: 14567  # HTTP (Tomcat) port

swagger:
  controllerPackage: train.controller

eureka:
  client:
    service-url:
      defaultZone: http://eureka-demo:8030/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    metadata-map:
      leaf: true
info:
  leaf: 1
  port: ${server.port}

logging:
  level:
    io.ztbeike.ffr4ms: debug