server:
  port: 15680

spring:
  application:
    name: ts-basic-service

swagger:
  controllerPackage: fdse.fdse.microservice.controller

eureka:
  client:
    service-url:
      defaultZone: http://eureka-demo:8030/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    metadata-map:
      leaf: false

info:
  leaf: 0
  port: ${server.port}

logging:
  level:
    io.ztbeike.ffr4ms: debug