spring:
  application:
    name: ts-notification-service

server:
  port: 40001

eureka:
  client:
    service-url:
      defaultZone: http://eureka-demo:8030/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}