server:
  port: 18673

spring:
  application:
    name: ts-inside-payment-service

  data:
    mongodb:
      host: ts-inside-payment-mongo
#     username: user
#     password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017

swagger:
  controllerPackage: inside_payment.controller

eureka:
  client:
    service-url:
      defaultZone: http://eureka-demo:8030/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}